clc;clear;close all;

disp('Build mexfasterCalculateOverlap');
mex mexfasterCalculateOverlap.cpp ...
    fasterCalculateOverlap.cpp ELPShape2Equation.cpp ...
    CalculateRangeOfY.cpp CalculateRangeAtY.cpp ...
    CalculateOverlap.cpp ...
    -I'D:\opencv3.1\opencv\build\include' -L'D:\opencv3.1\opencv\build\x64\vc14\lib' -lopencv_world310

disp('Build mexELPShape2Equation');
mex mexELPShape2Equation.cpp ...
    fasterCalculateOverlap.cpp ELPShape2Equation.cpp ...
    CalculateRangeOfY.cpp CalculateRangeAtY.cpp ...
    CalculateOverlap.cpp ...
    -I'D:\opencv3.1\opencv\build\include' -L'D:\opencv3.1\opencv\build\x64\vc14\lib' -lopencv_world310

disp('Build mexCalculateRangeOfY');
mex mexCalculateRangeOfY.cpp ...
    fasterCalculateOverlap.cpp ELPShape2Equation.cpp ...
    CalculateRangeOfY.cpp CalculateRangeAtY.cpp ...
    CalculateOverlap.cpp ...
    -I'D:\opencv3.1\opencv\build\include' -L'D:\opencv3.1\opencv\build\x64\vc14\lib' -lopencv_world310

disp('Build mexCalculateRangeAtY');
mex mexCalculateRangeAtY.cpp ...
    fasterCalculateOverlap.cpp ELPShape2Equation.cpp ...
    CalculateRangeOfY.cpp CalculateRangeAtY.cpp ...
    CalculateOverlap.cpp ...
    -I'D:\opencv3.1\opencv\build\include' -L'D:\opencv3.1\opencv\build\x64\vc14\lib' -lopencv_world310


disp('Build mexCalculateOverlap');
mex mexCalculateOverlap.cpp ...
    fasterCalculateOverlap.cpp ELPShape2Equation.cpp ...
    CalculateRangeOfY.cpp CalculateRangeAtY.cpp ...
    CalculateOverlap.cpp ...
    -I'D:\opencv3.1\opencv\build\include' -L'D:\opencv3.1\opencv\build\x64\vc14\lib' -lopencv_world310

